version: '3'
services:
  app:
    env_file: ./.env.dev
    build:
      context: .
    container_name: gnfinder-doc
    depends_on:
      - tika
  tika:
    image: apache/tika
    ports:
      - "9998:9998"
